### PR TITLE
Destroy translated model when deleting its last translation (could be

### PR DESCRIPTION
**Pull request by lcoq**
disabled with `translates(destroy_model_without_translation: false`))

### CODE REVIEW

**Comment by lcoq** [comment]
cc @bobbus

**Comment by bobbus** [comment]
@lcoq : LGTM

**Comment by lcoq** [comment]
@bobbus One commit added. Now if we want to destroy a translation and keep the `translations` collection clean of the translated model, we should use `Translatable#destroy_translation`.

**Comment by bobbus** [comment]
LGTM

**Pull request merged**
